/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-06-07 00:19:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.QuanLy;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NhapNhanVien_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/D:/HK2-Nam-3/CNPM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QLBNDC/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("jar:file:/D:/HK2-Nam-3/CNPM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QLBNDC/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1652342471921L));
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1654162162276L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1652342471852L));
    _jspx_dependants.put("jar:file:/D:/HK2-Nam-3/CNPM/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QLBNDC/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1390885082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Quản lý</title>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" />\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/icon?family=Material+Icons+Sharp\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<p>Phong</p>\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<input type=\"checkbox\" id=\"nav-toggle\">\r\n");
      out.write("		<!-- thanh menu -->\r\n");
      out.write("		<aside>\r\n");
      out.write("			<!--  logo  -->\r\n");
      out.write("			<div class=\"top\">\r\n");
      out.write("				<div class=\"logo\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"close\" id=\"close-btn\">\r\n");
      out.write("					<span class=\"material-icons-sharp\">close</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"sidebar\">\r\n");
      out.write("				<a href=\"QuanLy/TrangChu.htm\"> <span\r\n");
      out.write("					class=\"material-icons-sharp\">home</span>\r\n");
      out.write("					<h3>Trang chủ</h3>\r\n");
      out.write("				</a> <a href=\"QuanLy/SanPham.htm\"> <span\r\n");
      out.write("					class=\"material-icons-sharp\">local_drink</span>\r\n");
      out.write("					<h3>Sản phẩm</h3>\r\n");
      out.write("				</a> <a href=\"QuanLy/KhachHang.htm\"> <span\r\n");
      out.write("					class=\"material-icons-sharp\">people_alt</span>\r\n");
      out.write("					<h3>Khách hàng</h3>\r\n");
      out.write("				</a> <a href=\"QuanLy/NhanVien.htm\" class=\"active\"> <span\r\n");
      out.write("					class=\"material-icons-sharp\">folder_shared</span>\r\n");
      out.write("					<h3>Nhân viên</h3>\r\n");
      out.write("				</a> <a href=\"QuanLy/NhapKho.htm\"> <span\r\n");
      out.write("					class=\"material-icons-sharp\">add_business</span>\r\n");
      out.write("					<h3>Nhập kho</h3>\r\n");
      out.write("				</a> <a href=\"QuanLy/TonKho.htm\"> <span class=\"material-icons-sharp\">store</span>\r\n");
      out.write("					<h3>Tồn kho</h3>\r\n");
      out.write("				</a> <a href=\"QuanLy/DoanhSo.htm\"> <span\r\n");
      out.write("					class=\"material-icons-sharp\">inventory</span>\r\n");
      out.write("					<h3>Doanh số</h3>\r\n");
      out.write("				</a> <a href=\"QuanLy/Loai.htm\" > <span\r\n");
      out.write("					class=\"material-icons-sharp\">card_travel</span>\r\n");
      out.write("					<h3>Loại Sản Phẩm</h3>\r\n");
      out.write("				</a> </a> <a href=\"QuanLy/Hang.htm\"> <span\r\n");
      out.write("					class=\"material-icons-sharp\">fastfood</span>\r\n");
      out.write("					<h3>Hãng Sản Phẩm</h3>\r\n");
      out.write("				</a><a href=\"#\"> <span class=\"material-icons-sharp\">key</span>\r\n");
      out.write("					<h3>Đổi mật khuẩu</h3>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("		<!-- end aside  -->\r\n");
      out.write("\r\n");
      out.write("		<!-- -------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("		<!-- start main  -->\r\n");
      out.write("		<div class=\"main\">\r\n");
      out.write("			<!-- header  -->\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("				<h1>\r\n");
      out.write("					<label for=\"nav-toggle\"> <span class=\"material-icons-sharp\">reorder</span>\r\n");
      out.write("					</label>\r\n");
      out.write("				</h1>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"user-wrapper\">\r\n");
      out.write("					<img\r\n");
      out.write("						src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						alt=\"\">\r\n");
      out.write("					<!-- Example split danger button -->\r\n");
      out.write("					<!-- Example single danger button -->\r\n");
      out.write("					<div class=\"btn-group\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-warning dropdown-toggle\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\"\r\n");
      out.write("							style=\"width: 6.8rem; background: white; height: 2.8rem; border: none;\">\r\n");
      out.write("							Quản lý</button>\r\n");
      out.write("						<ul class=\"dropdown-menu\" style=\"width: 170px;\">\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"QuanLy/ThongTin.htm\"> <i><span\r\n");
      out.write("										class=\"material-icons-sharp\"> account_circle </span> <h6 style=\"float: right;  margin-top: 4px;\"> Thông tin cá nhân</h6></i> \r\n");
      out.write("										\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"Login/LogOut.htm\"\r\n");
      out.write("								style=\"text-align: center;\"> <i><span\r\n");
      out.write("										class=\"material-icons-sharp\"> logout </span>\r\n");
      out.write("										<h6 style=\"float: right; margin-top: 4px; margin-right: 23px;\">Đăng\r\n");
      out.write("											xuất</h6> </i>\r\n");
      out.write("							</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</header>");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			<div class=\"content\" style=\"background-image: linear-gradient(45deg, rgb(2, 136, 209), rgb(38, 198, 218)) !important;\">\r\n");
      out.write("				<h2 style=\"color: red;\">Nhân Viên</h2>\r\n");
      out.write("				<div class=\"bg-light p-5 rounded\" style=\"background-image: linear-gradient(45deg,#ff6f00,#ffca28)!important;\">\r\n");
      out.write("					\r\n");
      out.write("					<form action=\"QuanLy/NhapNhanVien.htm?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"POST\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Họ\r\n");
      out.write("									Nhân Viên</label>\r\n");
      out.write("								");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f0 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f0_reused = false;
      try {
        _jspx_th_spring_005fbind_005f0.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f0.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(104,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f0.setPath("nhanVien.HO");
        int[] _jspx_push_body_count_spring_005fbind_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f0 = _jspx_th_spring_005fbind_005f0.doStartTag();
          if (_jspx_eval_spring_005fbind_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("									<input name=\"HO\" type=\"text\" class=\"form-control\"\r\n");
              out.write("										id=\"exampleFormControlInput1\"\r\n");
              out.write("										placeholder=\"Vui lòng nhập họ nhân viên\" />\r\n");
              out.write("								");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f0.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f0);
        _jspx_th_spring_005fbind_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Tên\r\n");
      out.write("									Nhân Viên</label>\r\n");
      out.write("\r\n");
      out.write("								");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f1 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f1_reused = false;
      try {
        _jspx_th_spring_005fbind_005f1.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f1.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(115,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f1.setPath("nhanVien.TEN");
        int[] _jspx_push_body_count_spring_005fbind_005f1 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f1 = _jspx_th_spring_005fbind_005f1.doStartTag();
          if (_jspx_eval_spring_005fbind_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("									<input name=\"TEN\" type=\"text\" class=\"form-control\"\r\n");
              out.write("										id=\"exampleFormControlInput1\"\r\n");
              out.write("										placeholder=\"Vui lòng nhập tên nhân viên\" />\r\n");
              out.write("								");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f1.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f1[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f1.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f1.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f1);
        _jspx_th_spring_005fbind_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f1_reused);
      }
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Số\r\n");
      out.write("									Điện Thoại</label>\r\n");
      out.write("								");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f2 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f2_reused = false;
      try {
        _jspx_th_spring_005fbind_005f2.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f2.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(127,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f2.setPath("nhanVien.SDT");
        int[] _jspx_push_body_count_spring_005fbind_005f2 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f2 = _jspx_th_spring_005fbind_005f2.doStartTag();
          if (_jspx_eval_spring_005fbind_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("									<input name=\"SDT\" type=\"text\" class=\"form-control\"\r\n");
              out.write("										id=\"exampleFormControlInput1\"\r\n");
              out.write("										placeholder=\"Vui lòng nhập số điện thoại\" />\r\n");
              out.write("								");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f2.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f2[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f2.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f2.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f2);
        _jspx_th_spring_005fbind_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f2_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Địa\r\n");
      out.write("									Chỉ </label>\r\n");
      out.write("								");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f3 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f3_reused = false;
      try {
        _jspx_th_spring_005fbind_005f3.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f3.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(137,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f3.setPath("nhanVien.DIACHI");
        int[] _jspx_push_body_count_spring_005fbind_005f3 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f3 = _jspx_th_spring_005fbind_005f3.doStartTag();
          if (_jspx_eval_spring_005fbind_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("									<input name=\"DIACHI\" type=\"text\" class=\"form-control\"\r\n");
              out.write("										id=\"exampleFormControlInput1\"\r\n");
              out.write("										placeholder=\"Vui lòng nhập địa chỉ\" />\r\n");
              out.write("								");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f3.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f3[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f3.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f3.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f3);
        _jspx_th_spring_005fbind_005f3_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f3_reused);
      }
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">EMAIL\r\n");
      out.write("								</label>\r\n");
      out.write("								");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f4 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f4_reused = false;
      try {
        _jspx_th_spring_005fbind_005f4.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f4.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(148,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f4.setPath("nhanVien.EMAIL");
        int[] _jspx_push_body_count_spring_005fbind_005f4 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f4 = _jspx_th_spring_005fbind_005f4.doStartTag();
          if (_jspx_eval_spring_005fbind_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("									<input name=\"EMAIL\" type=\"text\" class=\"form-control\"\r\n");
              out.write("										id=\"exampleFormControlInput1\"\r\n");
              out.write("										placeholder=\"Vui lòng nhập email\" />\r\n");
              out.write("								");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f4.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f4[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f4.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f4.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f4);
        _jspx_th_spring_005fbind_005f4_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f4_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Chứng\r\n");
      out.write("									Minh Nhân Dân </label>\r\n");
      out.write("								");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f5 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f5_reused = false;
      try {
        _jspx_th_spring_005fbind_005f5.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f5.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(158,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f5.setPath("nhanVien.CMND");
        int[] _jspx_push_body_count_spring_005fbind_005f5 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f5 = _jspx_th_spring_005fbind_005f5.doStartTag();
          if (_jspx_eval_spring_005fbind_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("									<input name=\"CMND\" type=\"text\" class=\"form-control\"\r\n");
              out.write("										id=\"exampleFormControlInput1\"\r\n");
              out.write("										placeholder=\"Vui lòng nhập chứng minh nhân dân\" />\r\n");
              out.write("								");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f5.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f5[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f5.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f5.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f5);
        _jspx_th_spring_005fbind_005f5_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f5, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f5_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-md-3\">\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Ngày\r\n");
      out.write("									Sinh </label> <input type=\"date\" name=\"ngsinh\" class=\"form-control\" />\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("							<div class=\"col-md-6\">\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Lương</label>\r\n");
      out.write("\r\n");
      out.write("								");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f6 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f6_reused = false;
      try {
        _jspx_th_spring_005fbind_005f6.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f6.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(175,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f6.setPath("nhanVien.LUONG");
        int[] _jspx_push_body_count_spring_005fbind_005f6 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f6 = _jspx_th_spring_005fbind_005f6.doStartTag();
          if (_jspx_eval_spring_005fbind_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("									<input name=\"LUONG\" type=\"number\" class=\"form-control\"\r\n");
              out.write("										id=\"exampleFormControlInput1\"\r\n");
              out.write("										placeholder=\"Vui lòng nhập lương nhân viên\" />\r\n");
              out.write("								");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f6.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f6[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f6.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f6.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f6);
        _jspx_th_spring_005fbind_005f6_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f6, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f6_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Trạng\r\n");
      out.write("									Thái</label>\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-md-4\">\r\n");
      out.write("										");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f7 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f7_reused = false;
      try {
        _jspx_th_spring_005fbind_005f7.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f7.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(192,10) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f7.setPath("nhanVien.TRANGTHAI");
        int[] _jspx_push_body_count_spring_005fbind_005f7 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f7 = _jspx_th_spring_005fbind_005f7.doStartTag();
          if (_jspx_eval_spring_005fbind_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("											<input type=\"radio\" name=\"TRANGTHAI\" id=\"nghiviec\" value=\"0\">\r\n");
              out.write("										");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f7.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f7[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f7.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f7.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f7);
        _jspx_th_spring_005fbind_005f7_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f7, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f7_reused);
      }
      out.write("\r\n");
      out.write("										<label for=\"nghiviec\" class=\"form-label\">Nghỉ Việc </label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-4\">\r\n");
      out.write("										");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f8 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f8_reused = false;
      try {
        _jspx_th_spring_005fbind_005f8.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f8.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(198,10) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f8.setPath("nhanVien.TRANGTHAI");
        int[] _jspx_push_body_count_spring_005fbind_005f8 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f8 = _jspx_th_spring_005fbind_005f8.doStartTag();
          if (_jspx_eval_spring_005fbind_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("											<input type=\"radio\" name=\"TRANGTHAI\" value=\"1\" id=\"chuanghi\">\r\n");
              out.write("										");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f8.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f8[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f8.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f8.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f8);
        _jspx_th_spring_005fbind_005f8_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f8, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f8_reused);
      }
      out.write("\r\n");
      out.write("										<label for=\"chuanghi\" class=\"form-label\">Còn Làm </label>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Giới\r\n");
      out.write("									Tính</label>\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"col-md-4\">\r\n");
      out.write("										");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f9 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f9_reused = false;
      try {
        _jspx_th_spring_005fbind_005f9.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f9.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(213,10) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f9.setPath("nhanVien.GIOITINH");
        int[] _jspx_push_body_count_spring_005fbind_005f9 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f9 = _jspx_th_spring_005fbind_005f9.doStartTag();
          if (_jspx_eval_spring_005fbind_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("											<input type=\"radio\" name=\"GIOITINH\" id=\"nam\" value=\"1\">\r\n");
              out.write("										");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f9.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f9[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f9.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f9.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f9);
        _jspx_th_spring_005fbind_005f9_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f9, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f9_reused);
      }
      out.write("\r\n");
      out.write("										<label for=\"nam\" class=\"form-label\">Nam </label>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-md-4\">\r\n");
      out.write("										");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f10 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f10_reused = false;
      try {
        _jspx_th_spring_005fbind_005f10.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f10.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(219,10) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f10.setPath("nhanVien.GIOITINH");
        int[] _jspx_push_body_count_spring_005fbind_005f10 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f10 = _jspx_th_spring_005fbind_005f10.doStartTag();
          if (_jspx_eval_spring_005fbind_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("											<input type=\"radio\" name=\"GIOITINH\" value=\"0\" id=\"nu\">\r\n");
              out.write("										");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f10.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f10[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f10.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f10.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f10);
        _jspx_th_spring_005fbind_005f10_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f10, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f10_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("										<label for=\"nu\" class=\"form-label\">Nữ</label>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("							<div class=\"col-md-4\">\r\n");
      out.write("								<label for=\"exampleFormControlInput1\" class=\"form-label\">Tên\r\n");
      out.write("									Đăng Nhập</label>\r\n");
      out.write("								");
      //  spring:bind
      org.springframework.web.servlet.tags.BindTag _jspx_th_spring_005fbind_005f11 = (org.springframework.web.servlet.tags.BindTag) _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.get(org.springframework.web.servlet.tags.BindTag.class);
      boolean _jspx_th_spring_005fbind_005f11_reused = false;
      try {
        _jspx_th_spring_005fbind_005f11.setPageContext(_jspx_page_context);
        _jspx_th_spring_005fbind_005f11.setParent(null);
        // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(232,8) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spring_005fbind_005f11.setPath("taiKhoan.TenDN");
        int[] _jspx_push_body_count_spring_005fbind_005f11 = new int[] { 0 };
        try {
          int _jspx_eval_spring_005fbind_005f11 = _jspx_th_spring_005fbind_005f11.doStartTag();
          if (_jspx_eval_spring_005fbind_005f11 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            org.springframework.web.servlet.support.BindStatus status = null;
            status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
            do {
              out.write("\r\n");
              out.write("									<input name=\"TenDN\" type=\"text\" class=\"form-control\"\r\n");
              out.write("										id=\"exampleFormControlInput1\"\r\n");
              out.write("										placeholder=\"Vui lòng nhập tên đăng nhập\" />\r\n");
              out.write("								");
              int evalDoAfterBody = _jspx_th_spring_005fbind_005f11.doAfterBody();
              status = (org.springframework.web.servlet.support.BindStatus) _jspx_page_context.findAttribute("status");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spring_005fbind_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spring_005fbind_005f11[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spring_005fbind_005f11.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spring_005fbind_005f11.doFinally();
        }
        _005fjspx_005ftagPool_005fspring_005fbind_0026_005fpath.reuse(_jspx_th_spring_005fbind_005f11);
        _jspx_th_spring_005fbind_005f11_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fbind_005f11, _jsp_getInstanceManager(), _jspx_th_spring_005fbind_005f11_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("							<div class=\"col-1\">\r\n");
      out.write("								<button type=\"submit\" class=\"btn btn-primary\">Lưu</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- <script>\r\n");
      out.write("            function toggleMenu(){\r\n");
      out.write("                let toggle = document.querySelector('.toggle');\r\n");
      out.write("                toggle.classList.toggle\r\n");
      out.write("            }\r\n");
      out.write("        </script> -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Optional JavaScript -->\r\n");
      out.write("		<!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("		<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
      out.write("			integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
      out.write("			crossorigin=\"anonymous\"></script>\r\n");
      out.write("		<script\r\n");
      out.write("			src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\r\n");
      out.write("			integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\r\n");
      out.write("			crossorigin=\"anonymous\"></script>\r\n");
      out.write("		<script\r\n");
      out.write("			src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\r\n");
      out.write("			integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\r\n");
      out.write("			crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(21,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resource/QuanLy/css/QuanLyNhapNhanVien.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/QuanLy/NhapNhanVien.jsp(45,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resource/QuanLy/image/Vinmart_logo_sieu_thi (1).png");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/include/header.jsp(11,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resource/QuanLy/image/logo-vingroup-inkythuatso-13-13-41-00.jpg");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
